development:
  adapter: postgresql
  encoding: unicode
  database: senado-cc_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: senado-cc_test
  host: localhost
  pool: 5
  timeout: 5000

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: senado-cc_production
#   pool: 5
#   timeout: 5000
